version: "3"
services:
  es01:
    image: ghcr.io/codelibs/fess-elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
      - "TZ=Asia/Tokyo"
    mem_limit: 1.5g
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esdictionary01:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - esnet
    logging:
      driver: awslogs # CloudWatchLogsへ保存。CloudWatchLogsへの書き込みポリシーをもったIAMロールが必要。
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: qiita-search
        tag: "{{.Name}}" # Log stream (コンテナ名としている)

volumes:
  esdata01:
    driver: local
  esdictionary01:
    driver: local
