version: "3"
services:
  fess01:
    image: public.ecr.aws/c4k4h8g1/inayuky/qiita-search/fess:13.12.1
    container_name: fess01
    environment:
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
      - "TZ=Asia/Tokyo"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - esnet
    depends_on:
      - es01
    logging:
      driver: awslogs # CloudWatchLogsへ保存。CloudWatchLogsへの書き込みポリシーをもったIAMロールが必要。
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: qiita-search
        tag: "{{.Name}}" # Log stream (コンテナ名としている)

networks:
  esnet:
    driver: bridge
